### ISSUE TITLE
Noticeable performance drop after updating to 0.3.75

### ISSUE THREAD

**Issue by clampi** [Choumiko/SmartTrains#11]
Description
After updating to 0.3.75, I get a performance drop with trains running. I have not noticed right after the update as I had no trains, but as the factory evolved, I started to feel the lag. Attached below are the pictures that hinted me to who the culprit was.

I usually have ~58FPS/UPS in games, but now it gets as low as 39 FPS, with smart trains script updates spiking at around 8-9K. I don't have many trains and the lines are small.

I use the bob mods loco and cargo, if that matters.

Related information
Using Factorio 0.12.26, SmartTrains 0.3.75
I also attached the mod list, for reference.

Please tell me how to aid with debugging the issue further, in order to get it solved.

![smarttrainsfpsdip](https://cloud.githubusercontent.com/assets/10470629/13814126/c3974374-eb8d-11e5-9670-e2163438fde3.jpg)
![smarttrainswithalltrainsstopped](https://cloud.githubusercontent.com/assets/10470629/13814130/c6f8d5fa-eb8d-11e5-9852-f6e6bc57750e.jpg)
[mod-list.zip](https://github.com/Choumiko/SmartTrains/files/176071/mod-list.zip)

**Comment by clampi** [comment]
As a performance baseline, here is a screen, with the same save, after I downgraded to 0.3.74, issued the command "hardReset" and re-added all the routes. The command was required, as simply downgrading didn't reduce the script calls to an acceptable level.
Note: the "hardReset" command had no noticeable effect in 0.3.75
![smarttrains_0 3 74_baseline](https://cloud.githubusercontent.com/assets/10470629/13818287/fc9c3e94-eb9d-11e5-99e1-c155ee6adf6d.jpg)

**Comment by Choumiko** [comment]
Should have been fixed with 6b67b054abda348086ed48b13cac07a9a5c9cf77
