### ISSUE TITLE
bug when no wait time is set

### ISSUE THREAD

**Issue by Flow86** [Choumiko/SmartTrains#14]
I added a station with "0" wait time (to force the train to take a specific route)

now I get 

```
__SmartTrains__/control.lua:764: Error while running the event handler: __SmartTrains__/gui.lua:216: attempt to perform arithmetic on field 'time_to_wait' (a nil value)
```

I had to delete all lines and readd them, afterwards it worked again ?

**Comment by Choumiko** [comment]
It works again even with the 0 wait time?
I can't replicate it, do you remember the number of stations in your schedule, the rules you had set.
Have you changed the waiting time to 0 after saving the line?

**Comment by Flow86** [comment]
well, I reproduced it:

you have to wait until a train is in a station with "wait unlimited".

add a station to the train and save the line again. now you have to wait until another train of the line reaches a station -> error occures - it seems updating the line goes somewhat wrong

the station with "wait unlimited" set has a very large number inside the waiting time at the moment of the save of the line.

**Comment by Choumiko** [comment]
almost certainly gone in the 0.13 versions
