### ISSUE TITLE
Move auto depart to line rules

### ISSUE THREAD

**Issue by crosma** [Choumiko/SmartTrains#19]
Auto depart should be moved to the line rules so it can be set per line? Currently if you use any rule, even just Goto signal value, auto depart will not function. 

Would re-brand the option as "No Change" and place it under Departure Conditions. It could even be a radio box with full\empty.

**Comment by Choumiko** [comment]
fixed in 94e73aaa6bafb49284cd725ad2e564c69ba1a24c
