### ISSUE TITLE
Improve smart train stop entity names

### ISSUE THREAD

**Issue by crosma** [Choumiko/SmartTrains#21]
Improve the names of the entities

Name the lamp something like "Smart train stop signal lamp"
Name the output combinator something like "Constant smart stop combinator"

Also, if possible, provide a short tool tip description for those two entities. These changes would make the use of the entities a fair bit clearer.

**Comment by Choumiko** [comment]
How about: "Smart stop signal lamp" and "Smart stop signal output"?
Tooltips are not possible as far as i'm aware, you can show additional info when hovering over a recipe, but since those have no recipe i don't think there is a way.

**Comment by crosma** [comment]
Aye, good names. And that sucks about the tooltips.
