### ISSUE TITLE
Train.lua attempt to index field ? nil

### ISSUE THREAD

**Issue by lstanden** [Choumiko/SmartTrains#22]
Can't grab exact error message as seen on DutchJer's stream, but Train.lua line 22 is throwing an exception under certain circumstances.. perhaps when no stations are set, and you add a cargo wagon or additional locomotive to an existing train.

**Comment by Choumiko** [comment]
Should be fixed: 76a84440530e56a5ac8d7508cfc20245a4f74470
Release pending, quite a bit going on right now
