### ISSUE TITLE
__SmartTrains__/Train.lua:187: attempt to index local 'rules' (a boolean value)

### ISSUE THREAD

**Issue by keryja** [Choumiko/SmartTrains#26]
It seems that `rules` on [Train.lua:187](https://github.com/Choumiko/SmartTrains/blob/aa6abb2818dcabd331496217661fecf24459a229/Train.lua#L187) is always either true or false, however it's being accessed as a table.

Mods enabled when error occured:
- More Locomotives 0.3.0
- The Fat Controller 0.4.13

**Comment by Choumiko** [comment]
What version are you using? This looks like one of the latest commits from master, which is not released yet, because untested

**Comment by keryja** [comment]
I'm not sure how I ended up with the master branch, rather than a release.

Anyway, thanks for the quick response!
