### ISSUE TITLE
Close Parallel Same Name Smart Stations don't work correctly

### ISSUE THREAD

**Issue by Nexela** [Choumiko/SmartTrains#30]
Minor issue but hopefully fixable for .13. Using the latest Factorio Exp build, and have noticed using current stable and pre-release of smart trains. Also have lots of other mods installed and I was not able to test just smart trains on its own.  

Make 2 parallel train lines with a 1 track gap between. Put 2 stations directly across from each other and give them the same name. Throw down 2 trains with with diff items and send them to the stations. 
The Smart station on the left will alternate contents of both trains in the combinator. The station on the right (2nd train) will be blank. 

If the stations are named differently or staggered slightly it works fine

![20160601161756_3](https://cloud.githubusercontent.com/assets/13972192/15724311/7eba2fc8-2814-11e6-86ad-58ebe8d74061.jpg)

**Comment by Choumiko** [comment]
I knew eventually someone will report it :) I saw the rather large range it searches trainstops in a few days ago. 3 tile radius around the loco i think. I'll change it in the next prerelease.
