### ISSUE TITLE
Fluid Wagon doesnt count as wagon

### ISSUE THREAD

**Issue by Julian-Grueter** [Choumiko/SmartTrains#52]
![bug](https://cloud.githubusercontent.com/assets/9675148/25577399/f88fee0c-2e65-11e7-9202-d6e96070eec4.png)

The Marked Inserter does not work, when a train with fluid Wagons makes a stop. 
I set it up to only insert fuel, when a train with the correct amount of wagons arrives, to prevent inserting fuel into cargo wagons.
Not Necessarily a Bug, but it would be great if we could count the total amount of wagons of either Type :)
Tested on 0.15.5 Factorio and 2.0.0 Smarter Trains

**Comment by Choumiko** [comment]
fixed in 8dcab1072138d2a79bf11929d33526dbef1a58d5

Thanks for the report
