### ISSUE TITLE
Refuel overlay in Trains

### ISSUE THREAD

**Issue by Goten87** [Choumiko/SmartTrains#55]
we now have a trains control center will be nice if we can see on there what trains have refeul enabled and what train dont have it maby with the Fill crude oul barrel icon on it or a fuel block

or what if we can set it our selfs in the setting what we want as a icon 
i hate to open all my trains to see if it has refueling on becose sometimes i forget it

**Comment by Choumiko** [comment]
The vanilla gui can't be changed by mods. I can add a button to enable/disable Autorefuel for all trains if that helps

**Comment by Goten87** [comment]
yeah thats a option as well its just i hate to do ea train on its own
sins i forget it somtimes :P then after a time the train comes to a stop on the track
