### ISSUE TITLE
Incorrect number of tracked trains

### ISSUE THREAD

**Issue by dirtcrusher** [Choumiko/SmartTrains#64]
I noticed a small issue regarding the number of tracked trains (global or for a certain line):

When adding double-headed trains (L-C-L for example) to a line, the number of trains for that line increases by 2. When deconstructing said train (by hand), the number of trains of that line only decrements by 1. This does not happen when the locos are facing the same direction.

The same happens for the number of tracked trains in the ST-settings GUI.
I tried this on an empty test map (in 0.16.20 with only SmartTrains, Creative Mode and Creative World active), and was able to have a non-zero number of tracked trains even though no more trains existed on that map.

**Comment by Choumiko** [comment]
That's a known bug and mostly only a visual issue. It will be fixed sometime when i decide to rewrite the way SmartTrains tracks trains
