### ISSUE TITLE
Error : While running event SmartTrains::Custom event (ID 182)

### ISSUE THREAD

**Issue by jocker-il** [Choumiko/SmartTrains#70]
I couldn't find a way to copy the text that appears as it's in the chat and I don't know how to grab that, so here's a picture of the error:

![image](https://user-images.githubusercontent.com/13031901/62864585-6b5c9e80-bd0c-11e9-885e-eca914136c69.png)

and here is the reason:

 Once I added the fourth or fifth line to the "Base wall depot" station 

![image](https://user-images.githubusercontent.com/13031901/62864621-87f8d680-bd0c-11e9-86fe-1eaa10dc10c5.png)

it started ringing and showing those errors and doesn't stop until I close the locomotive GUI. It also rings more if you add more rules which I did since I have more that I need here...

Here is a link to that save file, you might need it - let me know
https://drive.google.com/open?id=1Ts7iuNEFoiQJJolf2_YjYMOY1vIRUkBk

**Comment by Choumiko** [comment]
Thanks for the report, should be fixed in the latest update.

In case the gui is still there after you open/close a train, use /st_reset_gui and it should work again (I didn't need to in the save you provided, but just in case)
